### ISSUE TITLE
There is no scroll inside Bottomsheet.

### ISSUE THREAD

**Issue by itsShivamBhalla** [harveyappleton/react-native-sheet#2]
![image](https://user-images.githubusercontent.com/40698245/161710409-b560f78b-e809-4bfe-978d-994b67f605cd.png)

There is a lot of text below but I'm unable to scroll.

**Comment by harveyappleton** [comment]
hey @itsShivamBhalla . youll need to manually set the height of the sheet via the `height` prop, and in order for the text to be scrollable, you'll want to use a ScrollView from React Native :)

**Comment by itsShivamBhalla** [comment]
> hey @itsShivamBhalla . youll need to manually set the height of the sheet via the `height` prop, and in order for the text to be scrollable, you'll want to use a ScrollView from React Native :)

I solved the issue by using Flatlist. However, content is still not scrolling in iOS simulator and in case of web Flatlist scroll is working fine

**Comment by MussadiqAli** [comment]
use ScrollView inside bottomsheet and pass the prop  contentContainerStyle={{ flexGrow: 1 }} to scrollview. It works fine for me
